### ISSUE TITLE
MQ 2102 Error when connecting the queue manager

### ISSUE THREAD

**Issue by jochen1234** [felix-lessoer/qbeat#2]
Hi Felix,

did you every tried your beat with libbeat 7.x on linux. I have an own beat implementation with a mq input and I have this mq problem. I have installed your beat same problem. Our old implementation was on 5.6 the mq part works.

Perhaps you can help. Thank you in advance.

[admin@localhost qbeat]$ ./qbeat 
Exiting: Cannot access queue manager. Error: MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_RESOURCE_PROBLEM [2102]
[admin@localhost qbeat]$ uname -a
Linux localhost.localdomain 5.6.19-200.fc31.x86_64 #1 SMP Wed Jun 17 16:54:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by felix-lessoer** [comment]
Hi Jochen,

this is an MQ related problem. 
Can you share your MQ logs?

**Comment by jochen1234** [comment]
Hi Felix,

it seems to be but I think we have a linux problem. Same host, same go version, same MQ version, same golang mq version

1) A native go mq program works

2) Our beat with libbeat 5.6 mq connection works

3) Our beat/your beat with libbeat 7.6 doesn't work 

I think it this with threads in linux handled with libbeat 7.6 in another way.

Below discussing with IBM support output of mq trace.
-----

Update:

The documents provided show the following

| Probe Id     :- XC035011                        |

| Application Name :- MQM                          |

| Component     :- xcsCreateThread                    |

...

| Major Errorcode  :- xecF_E_UNEXPECTED_SYSTEM_RC              |

| Minor Errorcode  :- OK                           |

| Probe Type    :- MSGAMQ6119                       |

| Probe Severity  :- 1                           |

| Probe Description :- AMQ6119S: An internal IBM MQ error has occurred ('1 - |

|  Operation not permitted' from pthread_create.)              |

| FDCSequenceNumber :- 0                           |

| Arith1      :- 1 (0x1)                        |

| Comment1     :- '1 - Operation not permitted' from pthread_create.   |

 

The above FDC indicates that xcsCreateThread() call is failing. MQ xcsCreateThread() call 

inherently uses OS call 'pthread_create' to create a thread. But this operation failed 

with '1 - Operation not permitted' from 'pthread_create'. The error 1 translates to 'EPERM'.

[EPERM]

  The caller does not have appropriate permission to set the required scheduling 

  parameters or scheduling policy.  

 

These errors are from OS which is below the MQ code. The strace would show the same 

as 'pthread_create' failing. So please involve OS support team investigate the above error 

and identify differences in MQ setup between Framework Beat 5.6 and Beat 7.x.

**Comment by felix-lessoer** [comment]
Hello Jochen,

the version gap from 5.6 to 7.x is very big. Where you able to identify the last working version of the beat framework?
My test users are running with Beat Framework v7.4 on Linux. Maybe it depends also on your specific os version?

**Comment by jochen1234** [comment]
Hi Felix,

I am using a Fedora 31 image nothing special and MQ 9.1.0.4. Has your Linux some special kernel settings? I will check 7.4 we are using  master. Are you using 7.4.0 or 7.4.2.

In any case it is good to hear that there is a working config config.

Cheers Jochen

**Comment by felix-lessoer** [comment]
Hi Jochen,

can you test what happens if you set
seccomp.enabled: false
in qbeat.yml?

Best regards
Felix

**Comment by jochen1234** [comment]
Hi Felix,

this works. Thank you very much. I will report this to Mark and add this in the documentation of the mq golang api.

Cheers Jochen

**Comment by madhuriChinna** [comment]
Hi Felix, we have a similar issue where receiving a 2102 error and enough resources.
first, it started with an authentication error and we rebooted the server, and it came back and running.
Later it went down again after a few hours with resources not available.
checked with the OS team nothing has changed from their end and a new update happened at the application end, not sure of the reason why this is happening any suggestions on how to check the actual reasons for this?

Thanks,
Madhuri

**Comment by madhuriChinna** [comment]
AMQ6026E: A resource shortage prevented the creation of a IBM MQ process.

EXPLANATION:
An attempt to create an MQ process was rejected by the operating system due to
a process limit (either the number of processes for each user or the total
number of processes running system wide), or because the system does not have
the resources necessary to create another process.
ACTION:
Investigate whether a process limit is preventing the creation of the process
and if so why the system is constrained in this way. Consider raising this
limit or reducing the workload on the system.
----- amqxfdcx.c : 842 --------------------------------------------------------
03/22/2023 09:17:13 AM - Process(28574.917) User(mqm) Program(amqzlaa0)

**Comment by felix-lessoer** [comment]
Can you share a bit more logs and qbeat config as well?

From what you have shared it sounds like there is a limit on the OS for the amount of processes..
This command may provide more info

`ulimit -a`
