### ISSUE TITLE
How to monitor two QMs from 1 Qbeat instance

### ISSUE THREAD

**Issue by MateszMiejski** [felix-lessoer/qbeat#4]
Hey, 
i see that there is a chance to monitor 2 QMs from 1 Qbeat. I have 2 QMs on same host. It is written that target QM must be accessible. What i need to do here ? I`ve made sender/receiver on both but do i need to put it on .yml somewhere? 

Regards, 
Matt

**Comment by felix-lessoer** [comment]
In the yml you need to set one of the queue managers as the binding queue manager.
In the target queue manager configuration you need to add both in the array.

**Comment by MateszMiejski** [comment]
Ye, we`ve made it. 
In .yml we have: 
#Defines the queue manager you want to connect to
  bindingQueueManager: "XXX01"

  #Defines the queue managers you want to monitor. If empty the binding queue manager will be used
  targetQueueManager: ["XXX01", "XXX02"]
  
And we have such error: 
2021-08-23T09:26:37.696+0200    INFO    beater/mqif.go:136      Connect to command queue of q mgr name: XXX02
2021-08-23T09:26:37.699+0200    INFO    beater/commands.go:238  MQCMD_RESET_Q_STATS initiated
2021-08-23T09:26:37.700+0200    INFO    beater/commands.go:245  Param MQCA_Q_NAME set to *
2021-08-23T09:26:37.700+0200    INFO    beater/commands.go:267  Error putting the command into command queue
2021-08-23T09:26:37.700+0200    INFO    beater/commands.go:268  MQPUT: MQCC = MQCC_FAILED [2] MQRC = MQRC_HOBJ_ERROR [2019]

The bridge should set automatically after putting an array in .yml?

**Comment by MateszMiejski** [comment]
Also i have 2 questions: 
do you have Qbeat.reference.yml which is mentioned in qbeat.yml.
Is it possible to send data to Kafka ?

**Comment by felix-lessoer** [comment]
I'm currently on vacation. Will answer next week if it is ok for you.

**Comment by MateszMiejski** [comment]
Ok, no problem :) Enyoy your vacations :)

**Comment by felix-lessoer** [comment]
1.) No I didn't created a reference.yml so far, but I tried to put everything in the yml file that is in the repo.
2.) Yes, it should be possible to send your data to Kafka. qbeat is using the same libs like every other beat. Those common functionality is working for every beat.
