### ISSUE TITLE
Step by step guide for compiling qbeat

### ISSUE THREAD

**Issue by ouwe-knutselaar** [felix-lessoer/qbeat#5]
L.S.

Is there a step by step guide how to compile the qbeat agent for Linux?
I try to compile it but I constant run into vague errors and it seems that I mis a set of prerequisites or steps.

Erwin

**Comment by felix-lessoer** [comment]
Well do you have MQ installed on the machine you are trying to compile?
Also would be helpful to see a few of the error messages.

**Comment by ouwe-knutselaar** [comment]
I've an MQ client installation 9.2 with the MQ SDK on Unbuntu 20.x

Maybe we can as a result of this chain create a compile manual

an example:
github.com/felix-lessoer/qbeat imports
	github.com/elastic/beats/libbeat/cmd/instance imports
	github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes imports
	k8s.io/client-go/kubernetes imports
	k8s.io/client-go/kubernetes/typed/batch/v2alpha1 imports
	k8s.io/api/batch/v2alpha1: module k8s.io/api@latest found (v0.22.1), but does not contain package k8s.io/api/batch/v2alpha1
github.com/felix-lessoer/qbeat imports
	github.com/elastic/beats/libbeat/cmd/instance imports
	github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes imports
	k8s.io/client-go/kubernetes imports
	k8s.io/client-go/kubernetes/typed/discovery/v1alpha1 imports
	k8s.io/api/discovery/v1alpha1: module k8s.io/api@latest found (v0.22.1), but does not contain package k8s.io/api/discovery/v1alpha1
go: finding module for package k8s.io/api/batch/v2alpha1
go: finding module for package k8s.io/api/discovery/v1alpha1
go: finding module for package k8s.io/api/discovery/v1alpha1
go: finding module for package k8s.io/api/batch/v2alpha1
../../../../pkg/mod/k8s.io/client-go@v0.20.6/kubernetes/scheme/register.go:37:2: module k8s.io/api@latest found (v0.22.1), but does not contain package k8s.io/api/batch/v2alpha1
../../../../pkg/mod/k8s.io/client-go@v0.20.6/kubernetes/scheme/register.go:43:2: module k8s.io/api@latest found (v0.22.1), but does not contain package k8s.io/api/discovery/v1alpha1
